version: '3.1'

services:

  db:
    image: mariadb:10.9.2
    restart: always
    environment:
      MYSQL_DATABASE: dbmovie
      MYSQL_USER: movie
      MYSQL_PASSWORD: azerty123!!
      MYSQL_ROOT_PASSWORD: azerty123!!
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306


  
  wildfly:
    build:
      context: ./deploy
    environment:
      - DB_NAME=dbmovie
      - DB_IP=db:3306
    depends_on: 
      - db
    ports:
     - 8080:8080
     - 9990:9990

